### ISSUE TITLE
Dependency no longer works for Cypress v12+

### ISSUE THREAD

**Issue by nilssonj-tgc** [FlorianGoussin/cypress-cy-select#21]
Error message: `Cannot overwrite the 'get' query. Queries cannot be overwritten.`
See: https://github.com/cypress-io/cypress/issues/25078

**Comment by nilssonj-tgc** [comment]
Fixed in [v12.6.0](https://docs.cypress.io/guides/references/changelog#12-6-0)

Here's the new [command](https://on.cypress.io/api/custom-queries): `Cypress.Commands.overwriteQuery`

**Comment by FlorianGoussin** [comment]
It should be fixed now.
