### ISSUE TITLE
Support complex jquery selectors

### ISSUE THREAD

**Issue by jp7677** [FlorianGoussin/cypress-cy-select#5]
Hi there,

Currently cy-select supports relatively simple selectors. I was thinking about other types of jQuery selectors, inspired by https://www.w3schools.com/jquery/jquery_ref_selectors.asp  and played a bit with regular expressions. The result would be https://github.com/jp7677/cypress-cy-select/commit/a030ca97f94a2cab7857538a1c73923db632bba0

Would you be interested in that direction? That said, I have no idea about performance, not sure how expensive the regex solution is compared to simple find and replace.

I could imagine that restricting the configuration option (e.g. enforcing just some specific characters as separator) would be needed to make this somewhat safe. Furthermore there are still scenarios that wont work in my playground.

**Comment by FlorianGoussin** [comment]
Hi there! 

I'm interested to go this direction. But I want to go step by step.
First by looking at your jest tests in the code you linked, I realized that the current code doesn't play well with the pseudo classes like :disabled for example. So I need to first address that. If possible without regexes.

I looked at the new tests in your code and I believed that most of it can be done without regexs. So probably this could be split between search and replace and regexes. For example with pseudo selectors like :disabled, the issue with the current code is that it first splits by spaces. Also the separator can be ":"

**Comment by FlorianGoussin** [comment]
Hi there! 

I'm interested to go in this direction, but I want to go step by step.
By looking at your jest tests in the code you linked, I realized that my code doesn't play well with the pseudo classes like :disabled for example. So I need to first address that. If possible without regexes. I'll get back to this as soon I'm done with this.

**Comment by FlorianGoussin** [comment]
@jp7677 I believe this should fix this issue: https://github.com/FlorianGoussin/cypress-cy-select/commit/0913de2ad16db366c73f7125ec02e91bd3fe4a64 and 8c1c344696342d01ac9272ad197fe744c41af818. I included most of your tests. Let me know if I missed something.

**Comment by jp7677** [comment]
Hi @FlorianGoussin I think your version does the job too. Very cool.
I'm seeing that you always `replace` over the complete `selectors` and not per segment. I guess it works because javascript always just replaces the first occurrence, unless you use a regex with `g` modifier. This could be somewhat confusing when reading the source. Though as stated. It seems to do the job.
Looking at the tests  I would split the tests between one where transformation should happen and a second test where no transformation should happen, e.g. https://github.com/jp7677/cypress-cy-select/commit/a9a262b7854c51a67bbdfa57cdb1923bd51ca64d
I could also imagine that restricting the configuration values (e.g. allow only `:` or `|` as separator and only e.g. `[a-z\-]+` as name/prefix) would prevent some user mistakes.

One new case that come to my mind: it would be cool if a selector like `div[cy|my-custom-selector]` would be transformed to `div[data-cy=my-custom-selector]`.

PS: Your prettier script in the package.json contains an error, the match should be like `./test/**/*.js`, currently it does not find the unit-test files.

**Comment by jp7677** [comment]
Closing this one due not that relevant anymore.
